/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.RepublicController;
import Models.UserModel;
import Views.Partials.ChooserEnterCreate;
import Views.Partials.MenuPanel;
import javax.swing.GroupLayout;
import javax.swing.JPanel;

/**
 *
 * @author Gabriel Barbosa Silva 2211114
 */
public class RepublicView extends javax.swing.JFrame {
    private UserModel user;
    private RepublicController republicController;
    
    public void setUser(UserModel user) {
        this.user = user;
        this.menuPanel1.setUser(this.user);
    }
    
    public UserModel getUser() {
        return this.user;
    }
    
    public void viewContentPanel() {
        if (this.user.getRepublicId() > 0) {
            System.out.println("Republic Id is not null");
        } else {
            ChooserEnterCreate chooser = new ChooserEnterCreate();
            chooser.setVisible(true);
            this.contentPanel.add(chooser);
            this.contentPanel.repaint();
            this.contentPanel.revalidate();
            this.menuPanel1.setChooserEnterCreateMenu();
        }
    }
    
    /**
     * Creates new form MuralView
     */
    public RepublicView(RepublicController republicController) {
        this.republicController = republicController;
        initComponents();
        this.menuPanel1.setRepublicView(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separator = new javax.swing.JSeparator();
        menuPanel1 = new Views.Partials.MenuPanel();
        contentPanel = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RepTasks");
        setResizable(false);

        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        contentPanel.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(separator, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contentPanel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void administratorPanel() {
        System.out.println("Administrator Panel");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane contentPanel;
    private Views.Partials.MenuPanel menuPanel1;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables
}
