/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.ManagementController;
import Controllers.ProfileController;
import Controllers.RepublicController;
import Controllers.TasksController;
import Models.FeedbackModel;
import Models.RepublicModel;
import Models.UserModel;
import Views.Partials.AdministrationPanel;
import Views.Partials.ChooserEnterCreate;
import Views.Partials.MenuPanel;
import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.JPanel;

/**
 *
 * @author Gabriel Barbosa Silva 2211114
 */
public class RepublicView extends javax.swing.JFrame {
    private UserModel user;
    private ArrayList<FeedbackModel> feedbacks;
    private RepublicModel republic;
    private RepublicController republicController;
    private ChooserEnterCreate chooserEnterCreate;
    private ProfileController profileController;
    private TasksController tasksController;
    private ManagementController managementController;
    
    public void setUser(UserModel user) {
        this.user = user;
        this.menuPanel1.setUser(this.user);
    }
    
    public void setFeedbacks(ArrayList<FeedbackModel> feedbacks) {
        this.feedbacks = feedbacks;
        this.menuPanel1.setFeedbacks(this.feedbacks);
    }
    
    public UserModel getUser() {
        return this.user;
    }
    
    public void setRepublic(RepublicModel republic) {
        this.republic = republic;
    }
    
    public RepublicModel getRepublic() {
        return this.republic;
    }
    
    public void viewTasksView() {
        JPanel panel = this.tasksController.getPanel();
        panel.setVisible(true);
        this.switchContentPanel(panel);
    }
    
    public void switchContentPanel(JPanel panel) {
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGap(221)
                .addComponent(panel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        this.repaint();
    }
    
    public void enterInRepublic(String name, String password) {
        this.republicController.create(name, password);
    }
    
    public void createRepublic(String name, String password) {
        this.republicController.create(name, password);
    }
    
    public void viewContentPanel() {
        if (this.user.getRepublicUuid() == null) {
            this.chooserEnterCreate.setVisible(true);
            this.switchContentPanel(this.chooserEnterCreate);
            this.menuPanel1.setChooserEnterCreateMenu();
            return;
        }
        
        if (!this.user.getUuid().equals(this.republic.getUserUuid())) {
            this.menuPanel1.setUserMenu();
        }
        
        this.viewTasksView();
    }
    
    /**
     * Creates new form MuralView
     */
    public RepublicView(RepublicController republicController) {
        this.republicController = republicController;
        this.chooserEnterCreate = new ChooserEnterCreate(this);
        this.chooserEnterCreate.setVisible(false);
        this.profileController = new ProfileController(this);
        this.managementController = new ManagementController(this);
        this.tasksController = new TasksController(this);
        initComponents();
        this.menuPanel1.setRepublicView(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separator = new javax.swing.JSeparator();
        menuPanel1 = new Views.Partials.MenuPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RepTasks");
        setResizable(false);

        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(488, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(separator, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void administratorPanel() {
        System.out.println("Administrator Panel");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Views.Partials.MenuPanel menuPanel1;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables
}
