/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Partials;

import Models.FeedbackModel;
import Models.TaskModel;
import Models.UserModel;
import Views.RepublicView;
import java.util.ArrayList;

/**
 *
 * @author Gabriel Barbosa Silva 2211114
 */
public class MenuPanel extends javax.swing.JPanel {
    private RepublicView republicView;
    private UserModel user;
    private ArrayList<FeedbackModel> feedbacks;
    
    public void setRepublicView(RepublicView republicView) {
        this.republicView = republicView;
    }
    
    public void setUser(UserModel user) {
        this.user = user;
        this.setProfile();
        this.setScore();
    }
    
    public void setFeedbacks(ArrayList<FeedbackModel> feedbacks) {
        this.feedbacks = feedbacks;
    }
    
    public void setProfile() {
        this.welcomeLabel.setText("Bem vindo, " + this.user.getUsername());
    }
    
    public void setScore() {
        double i = 0, media = 0;
        
        for (FeedbackModel feedback : this.feedbacks) {
            media += feedback.getScore();
            i++;
        }
        
        media /= i;
        
        this.scoreLabel.setText("Seu Score: " + media);
    }
    
    public void setChooserEnterCreateMenu() {
        this.adminButton.setVisible(false);
        this.myTasksButton.setVisible(false);
        this.tasksRepButton.setVisible(false);
    }
    
    public void setUserMenu() {
        this.adminButton.setVisible(false);
    }
    
    /**
     * Creates new form MenuPanel
     */
    public MenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        tasksRepButton = new javax.swing.JButton();
        myTasksButton = new javax.swing.JButton();
        myProfileButton = new javax.swing.JButton();
        scoreLabel = new javax.swing.JLabel();
        raptasksLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();

        adminButton.setText("Administrar República");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Sair");

        tasksRepButton.setText("Tarefas da República");

        myTasksButton.setText("Minhas Tarefas");

        myProfileButton.setText("Meu Perfil");

        scoreLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        scoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel.setText("Seu Score:");

        raptasksLabel.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        raptasksLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        raptasksLabel.setText("REPTASKS");

        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Bem vindo, usuário.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myProfileButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myTasksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tasksRepButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(raptasksLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(raptasksLabel)
                .addGap(18, 18, 18)
                .addComponent(welcomeLabel)
                .addGap(18, 18, 18)
                .addComponent(scoreLabel)
                .addGap(65, 65, 65)
                .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tasksRepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myTasksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        this.republicView.administratorPanel();
    }//GEN-LAST:event_adminButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton myProfileButton;
    private javax.swing.JButton myTasksButton;
    private javax.swing.JLabel raptasksLabel;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JButton tasksRepButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
